# Generated by Django 4.1.1 on 2022-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('ifsc', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('bank_id', models.PositiveIntegerField()),
                ('branch', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
            ],
        ),
    ]
